settings:
  connection:
    http:
      port: "8081"
  crypto:
    key: "1qa2ws3ed4rf5tg6yh"
    rotationLength: "12"
  fauna-db:
    clientKey: "jotto_svc_account"
    clientSecret: "fnAD6eF0rkACAuaAk7-gQFOxNLUh5jcgXIXqnrA8"
    host: "db.fauna.com"
    port: "443"
    baseUrl: ""
  results:
    charAbsent: "."
    charInvalid: "~"
    charPerfect: "*"
    charPresent: "o"